package binary_test

import (
	"bytes"
	"errors"
	"io"
	"os"
	"path/filepath"
	"testing"

	"github.com/galax-io/parsec/gatling"
	"github.com/galax-io/parsec/gatling/binary"
)

// The log is untrusted input: a decoder that panics on a damaged file takes the
// caller's process with it, and a caller cannot recover from a panic it did not
// expect. Every input either decodes or fails with an error — there is no third
// outcome, and no input reaches a panic.
//
// Seeded from the recordings, so the corpus is where the mutations start:
// randomly generated bytes rarely survive the first field, while a real log with
// one byte changed exercises the code that runs when a file is nearly right.
func FuzzDecode(f *testing.F) {
	logs, err := filepath.Glob(filepath.Join("..", "..", "testdata", "corpus", "gatling", "*", "simulation.log"))
	if err != nil {
		f.Fatal(err)
	}

	for _, log := range logs {
		raw, err := os.ReadFile(log) //nolint:gosec // a corpus path from the test's own glob
		if err != nil {
			f.Fatal(err)
		}

		f.Add(raw)
		// The first kilobyte on its own: a truncation that still holds a
		// complete header, which is where most of the interesting states are.
		if len(raw) > 1024 {
			f.Add(raw[:1024])
		}
	}

	// The cases no recording contains.
	f.Add([]byte(nil))
	f.Add([]byte{0x00})
	f.Add([]byte("RUN\tio.example.Sim\tsim\t1\t \t3.12.0\n"))
	f.Add(minimal("3.15.1"))

	f.Fuzz(func(t *testing.T, raw []byte) {
		rd, err := binary.NewReader(bytes.NewReader(raw))
		if err != nil {
			assertUsable(t, err)

			return
		}

		for n := 0; ; n++ {
			rec, err := rd.Next()
			if err != nil {
				if !errors.Is(err, io.EOF) {
					assertUsable(t, err)
				}

				return
			}

			if rec.Kind == gatling.KindUnknown {
				t.Fatalf("record %d decoded to no kind at all: %+v", n, rec)
			}

			// A decoder that can be made to loop is as bad as one that panics.
			if n > 1<<20 {
				t.Fatal("the reader yielded more than a million records from an input this small")
			}
		}
	})
}

// assertUsable requires a failure to be one a caller can act on: this package's
// own error, carrying a position, and never a bare string.
func assertUsable(t *testing.T, err error) {
	t.Helper()

	switch {
	case errors.As(err, new(*gatling.SyntaxError)),
		errors.As(err, new(*gatling.VersionError)),
		errors.As(err, new(*gatling.UnverifiedError)):
		return
	}

	t.Fatalf("a malformed log failed with %T: %v — a caller cannot tell what to do about it", err, err)
}
